import type { Metadata } from "next";
import "./globals.css";
import LayoutFooter from "@/components/layout/LayoutFooter";
import LayoutHeader from "@/components/layout/LayoutHeader";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="vi">
            <body className={inter.className}>
                <header className="fixed top-0 left-0 right-0 z-[9999]">
                    <LayoutHeader />
                </header>

                <main className="min-h-[calc(100vh-96px)] mt-[96px]">
                    {children}
                </main>

                <footer>
                    <LayoutFooter />
                </footer>
            </body>
        </html>
    );
}
